export const games = [
  {
    id: 1,
    title: "Pixel Quest",
    description: "An epic retro RPG adventure with classic pixel art and turn-based combat.",
    image: "/images/pixel-quest.svg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 2,
    title: "Neon Runner",
    description: "Fast-paced endless runner with vibrant neon visuals and retro soundtrack.",
    image: "/images/neon-runner.svg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 3,
    title: "Block Breaker",
    description: "Classic brick-breaking game reimagined with modern touch controls.",
    image: "/images/block-breaker.svg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 4,
    title: "Half-Life",
    description: "The revolutionary 1998 first-person shooter that changed gaming forever. Play as Gordon Freeman, a theoretical physicist who must escape the Black Mesa Research Facility after a disastrous experiment opens portals to an alien dimension. Features innovative storytelling through scripted sequences, intelligent AI enemies, and physics-based puzzles that set new standards for the FPS genre.",
    image: "https://upload.wikimedia.org/wikipedia/en/f/fa/Half-Life_Cover_Art.jpg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 5,
    title: "Retro Platformer",
    description: "Jump and dash your way through hand-crafted levels filled with secrets.",
    image: "/images/retro-platformer.svg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 6,
    title: "Puzzle Master",
    description: "Mind-bending puzzle game featuring retro aesthetics and addictive gameplay.",
    image: "/images/puzzle-master.svg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
  {
    id: 7,
    title: "Halo Combat Evolved",
    description: "Experience the legendary sci-fi first-person shooter that revolutionized gaming. Take control of Master Chief, a genetically-enhanced supersoldier, in a futuristic campaign against an alien alliance called the Covenant. Features advanced weaponry, iconic vehicles, and iconic multiplayer battles on Halo—a mysterious ringworld with secrets waiting to be uncovered.",
    image: "https://upload.wikimedia.org/wikipedia/en/8/80/Halo_-_Combat_Evolved_%28XBox_version_-_box_art%29.jpg",
    platforms: ["Android", "iOS"],
    appStoreLink: "#",
    playStoreLink: "#",
  },
];

export const team = [
  {
    id: 1,
    name: "Alex Johnson",
    role: "Founder & Creative Director",
    bio: "A passionate game developer with 15+ years of experience in retro gaming.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop",
  },
  {
    id: 2,
    name: "Sarah Chen",
    role: "Lead Developer",
    bio: "Expert in mobile game optimization and retro-inspired game mechanics.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop",
  },
  {
    id: 3,
    name: "Mike Rodriguez",
    role: "Game Designer",
    bio: "Specializes in creating engaging game experiences with classic vibes.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop",
  },
  {
    id: 4,
    name: "Emma Wilson",
    role: "UI/UX Designer",
    bio: "Blends retro aesthetics with modern design principles seamlessly.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop",
  },
];

export const blog = [
  {
    id: 1,
    title: "The Rise of Retro Gaming on Mobile",
    summary: "Explore why retro games are making a comeback and dominating mobile app stores.",
    date: "March 15, 2024",
    link: "#",
  },
  {
    id: 2,
    title: "How We Design Addictive Retro Mechanics",
    summary: "Behind the scenes look at our game design philosophy and development process.",
    date: "March 8, 2024",
    link: "#",
  },
  {
    id: 3,
    title: "The Art of Pixel Art in Modern Games",
    summary: "A deep dive into pixel art techniques and how we create stunning retro visuals.",
    date: "February 28, 2024",
    link: "#",
  },
  {
    id: 4,
    title: "Mobile Gaming Trends for 2024",
    summary: "Predictions and insights about the future of mobile gaming this year.",
    date: "February 20, 2024",
    link: "#",
  },
];
